language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/native-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-header

install:
  - pip install -U http://182.61.61.133/dl/platformio-core-develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR
