build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/native-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stc-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stc-header"

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=C:\Python36\Scripts;%PATH%
- cmd: pip3 install -U http://182.61.61.133/dl/platformio-core-develop.zip
- cmd: platformio platform install file://.

test_script:
- cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%
